# Generated by Django 5.2 on 2025-04-13 02:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique name of the category', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this category was last updated')),
            ],
            options={
                'verbose_name': 'Email Category',
                'verbose_name_plural': 'Email Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='email_app_e_name_2edf70_idx'), models.Index(fields=['name', 'description'], name='email_app_e_name_76150e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Priority level (High, Medium, Low)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the priority level')),
                ('weight', models.IntegerField(default=50, help_text='Numerical weight for sorting (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this priority was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this priority was last updated')),
            ],
            options={
                'verbose_name': 'Email Priority',
                'verbose_name_plural': 'Email Priorities',
                'ordering': ['-weight'],
                'indexes': [models.Index(fields=['name'], name='email_app_e_name_10f653_idx'), models.Index(fields=['weight'], name='email_app_e_weight_c5a03a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text="User's email address", max_length=254, unique=True)),
                ('gmail_connected', models.BooleanField(default=False, help_text='Whether Gmail is connected')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last Gmail sync timestamp', null=True)),
                ('email_signature', models.TextField(blank=True, help_text="User's email signature")),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences and settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this profile was last updated')),
                ('user', models.OneToOneField(help_text='Django user this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('gmail_id', models.CharField(help_text='Gmail message ID', max_length=100, unique=True)),
                ('id', models.BigAutoField(help_text='Internal primary key', primary_key=True, serialize=False)),
                ('subject', models.CharField(db_index=True, help_text='Email subject', max_length=255)),
                ('sender', models.CharField(db_index=True, help_text="Sender's email address and display name", max_length=255)),
                ('recipients', models.JSONField(help_text='List of recipient email addresses and display names')),
                ('body', models.TextField(blank=True, help_text='Email body content')),
                ('date', models.DateTimeField(db_index=True, help_text='Date and time the email was sent/received')),
                ('snippet', models.TextField(blank=True, help_text='Short preview of the email content')),
                ('has_attachments', models.BooleanField(default=False, help_text='Whether the email has attachments')),
                ('folder', models.CharField(db_index=True, default='INBOX', help_text='Gmail folder (INBOX, SENT, etc.)', max_length=50)),
                ('labels', models.JSONField(default=list, help_text='List of Gmail labels')),
                ('search_text', models.TextField(blank=True, help_text='Concatenated text for full-text search')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(help_text='Optimized vector for full-text search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('category', models.ForeignKey(help_text='Email category for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_app.emailcategory')),
                ('priority', models.ForeignKey(help_text='Email priority level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_app.emailpriority')),
                ('user', models.ForeignKey(help_text='User who owns this email', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_app.userprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_categorize', models.BooleanField(default=True, help_text='Whether to auto-categorize emails')),
                ('auto_priority', models.BooleanField(default=True, help_text='Whether to auto-set email priority')),
                ('voice_enabled', models.BooleanField(default=False, help_text='Whether voice commands are enabled')),
                ('notification_enabled', models.BooleanField(default=True, help_text='Whether notifications are enabled')),
                ('theme', models.CharField(default='light', help_text='UI theme preference', max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('language', models.CharField(default='en', help_text='Language preference', max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('ai_settings', models.JSONField(blank=True, default=dict, help_text='AI-related settings and preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When these settings were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When these settings were last updated')),
                ('user', models.OneToOneField(help_text='Django user these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(help_text='Internal primary key', primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original filename of the attachment', max_length=255)),
                ('mime_type', models.CharField(help_text='MIME type of the attachment', max_length=100)),
                ('size', models.BigIntegerField(help_text='Size of the attachment in bytes')),
                ('attachment_id', models.CharField(help_text='Gmail attachment ID', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('email', models.ForeignKey(help_text='Email this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_app.email')),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='email_app_e_email_i_2a2841_idx'), models.Index(fields=['mime_type'], name='email_app_e_mime_ty_3f76af_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='email_app_u_user_id_a0b1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email'], name='email_app_u_email_855692_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', '-date'], name='email_app_e_user_id_14d38c_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['folder'], name='email_app_e_folder_d73063_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['category'], name='email_app_e_categor_9db2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['priority'], name='email_app_e_priorit_f0f457_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='email_app_e_search__8f1bfc_gin'),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['user'], name='email_app_u_user_id_f4d885_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['theme'], name='email_app_u_theme_4e856e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersettings',
            index=models.Index(fields=['language'], name='email_app_u_languag_a83a39_idx'),
        ),
    ]
